# Generated by Django 5.1.5 on 2025-01-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_no', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('economy_class_seats', models.IntegerField()),
                ('economy_class_price', models.PositiveIntegerField()),
                ('business_class_seats', models.IntegerField()),
                ('business_class_price', models.PositiveIntegerField()),
                ('first_class_seats', models.IntegerField()),
                ('first_class_price', models.PositiveIntegerField()),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='airports.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airports.airport')),
            ],
        ),
    ]
