# Generated by Django 5.1.5 on 2025-01-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_class', models.CharField(choices=[('E', 'Economy'), ('F', 'First Class'), ('B', 'Business Class')], default='E', max_length=1)),
                ('pnr', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('list_of_passengers', models.JSONField(default=list)),
                ('flight_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
    ]
