# Generated by Django 5.1.5 on 2025-02-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_seats_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight_code',
            new_name='flight_no',
        ),
    ]
